// <auto-generated />
using System;
using LibraryManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20260723131142_AddNewspapers")]
    partial class AddNewspapers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("LibraryManagement.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.ToTable("Books12");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Andrew Hunt and David Thomas",
                            ISBN = "978-0201616224",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2021, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Robert C. Martin",
                            ISBN = "978-0132350884",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Design Pattern using C#"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Pranaya Kumar Rout",
                            ISBN = "978-0451616235",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2022, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mastering ASP.NET Core"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Rakesh Kumat",
                            ISBN = "978-4562350123",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2020, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "SQL Server with DBA"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Robert C. Martin",
                            ISBN = "978-0132350882",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2008, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Clean Code"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Martin Fowler",
                            ISBN = "978-0134757599",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2018, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Refactoring"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.BorrowRecord", b =>
                {
                    b.Property<int>("BorrowRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.HasKey("BorrowRecordId");

                    b.HasIndex("BookId");

                    b.ToTable("BorrowRecords12");
                });

            modelBuilder.Entity("LibraryManagement.Models.LibrarianModel", b =>
                {
                    b.Property<int>("LibrarianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("LibrarianId");

                    b.ToTable("Librarians", (string)null);

                    b.HasData(
                        new
                        {
                            LibrarianId = 1,
                            Age = 34,
                            Name = "Sarah Connor",
                            Phone = "555-0201"
                        },
                        new
                        {
                            LibrarianId = 2,
                            Age = 28,
                            Name = "John Doe",
                            Phone = "555-0202"
                        },
                        new
                        {
                            LibrarianId = 3,
                            Age = 45,
                            Name = "Michael Scott",
                            Phone = "555-0203"
                        },
                        new
                        {
                            LibrarianId = 4,
                            Age = 39,
                            Name = "Ellen Ripley",
                            Phone = "555-0204"
                        },
                        new
                        {
                            LibrarianId = 5,
                            Age = 40,
                            Name = "James Bond",
                            Phone = "555-0205"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.LoginModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("logintab", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            password = "12345",
                            username = "admin"
                        },
                        new
                        {
                            id = 2,
                            password = "myc546",
                            username = "mycodingproject"
                        },
                        new
                        {
                            id = 3,
                            password = "myc",
                            username = "my"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.Magazine", b =>
                {
                    b.Property<int>("MagazineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("MagazineId");

                    b.ToTable("Magazines");

                    b.HasData(
                        new
                        {
                            MagazineId = 1,
                            Description = "A magazine focusing on modern technology, AI, and future trends.",
                            ImageUrl = "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=500&auto=format&fit=crop&q=60",
                            IssueNumber = "104",
                            PublishedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Future Media",
                            Title = "Tech Today"
                        },
                        new
                        {
                            MagazineId = 2,
                            Description = "Explore the beautiful natural world with our weekly nature deep dives.",
                            ImageUrl = "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=500&auto=format&fit=crop&q=60",
                            IssueNumber = "Vol 45",
                            PublishedDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Green Earth Publishing",
                            Title = "Nature Weekly"
                        },
                        new
                        {
                            MagazineId = 3,
                            Description = "The premier source for sports news, athletic profiles, and game summaries.",
                            ImageUrl = "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=500&auto=format&fit=crop&q=60",
                            IssueNumber = "Issue 9",
                            PublishedDate = new DateTime(2023, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Athletic Press",
                            Title = "Sports Illustrated"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.Newspaper", b =>
                {
                    b.Property<int>("NewspaperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("NewspaperId");

                    b.ToTable("Newspapers");

                    b.HasData(
                        new
                        {
                            NewspaperId = 1,
                            Name = "The Daily Chronicle",
                            PublishedDate = new DateTime(2023, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Global News Network"
                        },
                        new
                        {
                            NewspaperId = 2,
                            Name = "Morning Herald",
                            PublishedDate = new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "City Press"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.StudentModel", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone_Number");

                    b.Property<string>("StudentName")
                        .HasColumnType("TEXT")
                        .HasColumnName("Student_Name");

                    b.HasKey("StudentId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "alice.j@email.com",
                            Phone = "555-0101",
                            StudentName = "Alice Johnson"
                        },
                        new
                        {
                            StudentId = 2,
                            Email = "bob.smith@email.com",
                            Phone = "555-0102",
                            StudentName = "Bob Smith"
                        },
                        new
                        {
                            StudentId = 3,
                            Email = "charlie.b@email.com",
                            Phone = "555-0103",
                            StudentName = "Charlie Brown"
                        },
                        new
                        {
                            StudentId = 4,
                            Email = "diana.p@email.com",
                            Phone = "555-0104",
                            StudentName = "Diana Prince"
                        },
                        new
                        {
                            StudentId = 5,
                            Email = "evan.w@email.com",
                            Phone = "555-0105",
                            StudentName = "Evan Wright"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.BorrowRecord", b =>
                {
                    b.HasOne("LibraryManagement.Models.Book", "Book")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryManagement.Models.Book", b =>
                {
                    b.Navigation("BorrowRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
