// <auto-generated />
using System;
using LibraryManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("LibraryManagement.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("BookId");

                    b.ToTable("Books12");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Andrew Hunt and David Thomas",
                            ISBN = "978-0201616224",
                            ImageUrl = "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&q=80",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2021, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Robert C. Martin",
                            ISBN = "978-0132350884",
                            ImageUrl = "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=500&q=80",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Design Pattern using C#"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Pranaya Kumar Rout",
                            ISBN = "978-0451616235",
                            ImageUrl = "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=500&q=80",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2022, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mastering ASP.NET Core"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Rakesh Kumat",
                            ISBN = "978-4562350123",
                            ImageUrl = "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=500&q=80",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2020, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "SQL Server with DBA"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Robert C. Martin",
                            ISBN = "978-0132350882",
                            ImageUrl = "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500&q=80",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2008, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Clean Code"
                        },
                        new
                        {
                            BookId = 6,
                            Author = "Martin Fowler",
                            ISBN = "978-0134757599",
                            ImageUrl = "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=500&q=80",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2018, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Refactoring"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.BorrowRecord", b =>
                {
                    b.Property<int>("BorrowRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.HasKey("BorrowRecordId");

                    b.HasIndex("BookId");

                    b.ToTable("BorrowRecords12");
                });

            modelBuilder.Entity("LibraryManagement.Models.LibrarianModel", b =>
                {
                    b.Property<int>("LibrarianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("LibrarianId");

                    b.ToTable("Librarians", (string)null);

                    b.HasData(
                        new
                        {
                            LibrarianId = 1,
                            Age = 34,
                            Name = "Sarah Connor",
                            Phone = "555-0201"
                        },
                        new
                        {
                            LibrarianId = 2,
                            Age = 28,
                            Name = "John Doe",
                            Phone = "555-0202"
                        },
                        new
                        {
                            LibrarianId = 3,
                            Age = 45,
                            Name = "Michael Scott",
                            Phone = "555-0203"
                        },
                        new
                        {
                            LibrarianId = 4,
                            Age = 39,
                            Name = "Ellen Ripley",
                            Phone = "555-0204"
                        },
                        new
                        {
                            LibrarianId = 5,
                            Age = 40,
                            Name = "James Bond",
                            Phone = "555-0205"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.LoginModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("logintab", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            password = "12345",
                            username = "admin"
                        },
                        new
                        {
                            id = 2,
                            password = "myc546",
                            username = "mycodingproject"
                        },
                        new
                        {
                            id = 3,
                            password = "myc",
                            username = "my"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Publications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=500&q=80",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Global Media Group",
                            Title = "The Daily Times",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1546422904-90eab23c3d7e?w=500&q=80",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "WallSt Press",
                            Title = "Financial Chronicle",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=500&q=80",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Silicon Valley Pubs",
                            Title = "Tech Weekly News",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?w=500&q=80",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "City Press House",
                            Title = "Metro Morning Post",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=500&q=80",
                            IsAvailable = false,
                            PublishedDate = new DateTime(2026, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Global Media Group",
                            Title = "Saturday Sports Herald",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=500&q=80",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "NatGeo Society",
                            Title = "National Geographic Vol 45",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=500&q=80",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Condé Nast",
                            Title = "Vogue Fashion Summer",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=500&q=80",
                            IsAvailable = false,
                            PublishedDate = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Forbes Media",
                            Title = "Forbes Business 30 Under 30",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=500&q=80",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Future US",
                            Title = "PC Gamer Ultimate",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://images.unsplash.com/photo-1532012197267-da84d127e765?w=500&q=80",
                            IsAvailable = true,
                            PublishedDate = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Springer Nature",
                            Title = "Scientific American",
                            Type = 1
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.StudentModel", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("Phone_Number");

                    b.Property<string>("StudentName")
                        .HasColumnType("TEXT")
                        .HasColumnName("Student_Name");

                    b.HasKey("StudentId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "alice.j@email.com",
                            Phone = "555-0101",
                            StudentName = "Alice Johnson"
                        },
                        new
                        {
                            StudentId = 2,
                            Email = "bob.smith@email.com",
                            Phone = "555-0102",
                            StudentName = "Bob Smith"
                        },
                        new
                        {
                            StudentId = 3,
                            Email = "charlie.b@email.com",
                            Phone = "555-0103",
                            StudentName = "Charlie Brown"
                        },
                        new
                        {
                            StudentId = 4,
                            Email = "diana.p@email.com",
                            Phone = "555-0104",
                            StudentName = "Diana Prince"
                        },
                        new
                        {
                            StudentId = 5,
                            Email = "evan.w@email.com",
                            Phone = "555-0105",
                            StudentName = "Evan Wright"
                        });
                });

            modelBuilder.Entity("LibraryManagement.Models.BorrowRecord", b =>
                {
                    b.HasOne("LibraryManagement.Models.Book", "Book")
                        .WithMany("BorrowRecords")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryManagement.Models.Book", b =>
                {
                    b.Navigation("BorrowRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
